# Generated by Django 5.2.7 on 2025-10-22 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_field', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_code', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('framework', models.CharField(choices=[('django', 'Django + DRF'), ('express', 'Express.js + Sequelize')], default='django', max_length=20)),
                ('include_docker', models.BooleanField(default=False)),
                ('include_cors', models.BooleanField(default=True)),
                ('include_rate_limiting', models.BooleanField(default=False)),
                ('include_logging', models.BooleanField(default=False)),
                ('include_env_example', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('foreign_key', 'Foreign Key'), ('one_to_one', 'One-to-One'), ('many_to_many', 'Many-to-Many')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('on_delete', models.CharField(choices=[('cascade', 'CASCADE'), ('protect', 'PROTECT'), ('set_null', 'SET_NULL'), ('set_default', 'SET_DEFAULT')], default='cascade', max_length=20)),
                ('related_name', models.CharField(blank=True, max_length=255)),
                ('null', models.BooleanField(default=True)),
                ('blank', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('char', 'CharField'), ('text', 'TextField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField'), ('date', 'DateField'), ('datetime', 'DateTimeField'), ('email', 'EmailField'), ('url', 'URLField'), ('image', 'ImageField'), ('file', 'FileField'), ('decimal', 'DecimalField'), ('float', 'FloatField'), ('json', 'JSONField')], default='char', max_length=20)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('null', models.BooleanField(default=False)),
                ('blank', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('database_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='scaffolder.databasemodel')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
