# Generated by Django 5.2.7 on 2025-10-22 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scaffolder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='scaffolder.project'),
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_models', to='scaffolder.project'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='scaffolder.databasemodel'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='scaffolder.databasemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='modelfield',
            unique_together={('database_model', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedproject',
            unique_together={('project', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='databasemodel',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_model', 'name')},
        ),
    ]
