# Generated by Django 5.2.7 on 2025-10-24 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolder', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('view_type', models.CharField(choices=[('list', 'List View'), ('detail', 'Detail View'), ('create', 'Create View'), ('update', 'Update View'), ('destroy', 'Delete View')], default='list', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('pagination_enabled', models.BooleanField(default=True)),
                ('page_size', models.IntegerField(default=20)),
                ('ordering_fields', models.JSONField(blank=True, default=list)),
                ('search_fields', models.JSONField(blank=True, default=list)),
                ('filter_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='scaffolder.databasemodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='scaffolder.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ViewField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scaffolder.modelfield')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_fields', to='scaffolder.view')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('view', 'model_field')},
            },
        ),
    ]
