# Generated by Django 5.2.7 on 2025-10-24 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolder', '0003_view_viewfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], default='GET', max_length=10)),
                ('permission_level', models.CharField(choices=[('Public', 'Public'), ('Authenticated', 'Authenticated'), ('Admin Only', 'Admin Only')], default='Public', max_length=20)),
                ('associated_view', models.CharField(blank=True, max_length=255)),
                ('namespace', models.CharField(blank=True, max_length=100)),
                ('custom_regex', models.CharField(blank=True, max_length=200)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_routes', to='scaffolder.project')),
            ],
            options={
                'ordering': ['path', 'http_method'],
                'unique_together': {('project', 'path', 'http_method')},
            },
        ),
    ]
