# Generated by Django 5.2.7 on 2025-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolder', '0004_urlroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='primary_key',
            field=models.BooleanField(default=False),
        ),
    ]
