# Generated by Django 5.2.7 on 2025-10-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolder', '0005_modelfield_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='relationship_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
